name: audio_flux_fork
description: >-
  Audio visualizer which uses flutter_soloud and
  flutter_recorder to acquire the audio data and
  display them using a CustomPainter or
  shader_buffer to render them to shaders.

  Fork of audio_flux_fork.
version: 1.2.2
homepage: https://github.com/thomashandlag/audio_flux_fork
repository: https://github.com/thomashandlag/audio_flux_fork
topics:
  - audio
  - visualizer
  - shader

screenshots:
  - description: "shader visualizer"
    path: img/shader.png

environment:
  sdk: ^3.6.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_soloud: ^4.0.7
  shader_buffers_fork: ^0.0.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
